-- Active: 1709030200372@@127.0.0.1@3306@sig_kampung_adat_kabupaten_alor
CREATE TABLE tentang(
  id INT AUTO_INCREMENT PRIMARY KEY,
  deskripsi TEXT
);

CREATE TABLE kontak (
  id_kontak INT AUTO_INCREMENT PRIMARY KEY,
  nama VARCHAR(75),
  email VARCHAR(50),
  phone CHAR(12),
  pesan TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE kategori_fasilitas(
  id_kf INT AUTO_INCREMENT PRIMARY KEY,
  nama_kf VARCHAR(50)
);

CREATE TABLE kampung_adat (
  id_kampung_adat INT AUTO_INCREMENT PRIMARY KEY,
  img_kampung VARCHAR(75) NOT NULL,
  nama_kampung VARCHAR(100) NOT NULL,
  lokasi VARCHAR(100) NOT NULL,
  latitude CHAR(20),
  longitude CHAR(20),
  deskripsi TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE fasilitas_ka(
  id_fasilitas_ka INT AUTO_INCREMENT PRIMARY KEY,
  id_kampung_adat INT,
  id_kf INT,
  FOREIGN KEY (id_kampung_adat) REFERENCES kampung_adat(id_kampung_adat) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (id_kf) REFERENCES kategori_fasilitas(id_kf) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE kunjungan(
  id_kunjungan INT AUTO_INCREMENT PRIMARY KEY,
  id_kampung_adat INT,
  jumlah_kunjungan INT,
  tgl DATE DEFAULT CURRENT_TIMESTAMP,
  waktu TIME DEFAULT CURRENT_TIMESTAMP,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (id_user) REFERENCES users(id_user) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (id_kampung_adat) REFERENCES kampung_adat(id_kampung_adat) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE galeri(
  id_galeri INT AUTO_INCREMENT PRIMARY KEY,
  image VARCHAR(75),
  ket TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);